[package]
name = "lvgl"
description = "LVGL bindings for Rust. A powerful and easy-to-use embedded GUI with many widgets, advanced visual effects (opacity, antialiasing, animations) and low memory requirements (16K RAM, 64K Flash)."
version = "0.7.0"
authors = ["Rafael Caricio <crates.lvgl@caric.io>", "Nia Espera <a5b6@riseup.net>"]
edition = "2021"
repository = "https://github.com/umbrella22/lv_binding_rust"
license = "MIT"
readme = "../README.md"
categories = ["api-bindings", "embedded", "gui", "no-std"]
keywords = ["littlevgl", "lvgl"]
build = "build.rs"

[dependencies]
lvgl-sys = { version = "0.7.0", path = "../lvgl-sys" }
cty = "0.2.2"
embedded-graphics = { version = "0.8.0", optional = true }
cstr_core = { version = "0.2.6", default-features = false, features = ["alloc"] }
bitflags = "2.6"
paste = "1.0"
ctor = "0.2"

[features]
default = ["embedded_graphics", "drivers"]

embedded_graphics = ["embedded-graphics"]
drivers = ["lvgl-sys/drivers"]
sdl = ["lvgl-sys/sdl"]
demo-widgets = ["lvgl-sys/lv-demo-widgets"]
alloc = ["cstr_core/alloc"]
lvgl_alloc = ["alloc"]
use-vendored-config = ["lvgl-sys/use-vendored-config"]
rust_timer = ["lvgl-sys/rust_timer"]
custom_timer = ["lvgl-sys/custom_timer"]
nightly = []
unsafe_no_autoinit = []
custom_allocator = []

[build-dependencies]
quote = "1.0"
proc-macro2 = "1.0"
lvgl-codegen = { version = "0.7.0", path = "../lvgl-codegen" }
lvgl-sys = { version = "0.7.0", path = "../lvgl-sys" }

[dev-dependencies]
embedded-graphics-simulator = "0.5.0"

[[example]]
name = "app"
path = "../examples/app.rs"
required-features = ["alloc", "embedded_graphics"]

[[example]]
name = "demo"
path = "../examples/demo.rs"
required-features = ["alloc", "embedded_graphics"]

[[example]]
name = "bar"
path = "../examples/bar.rs"
required-features = ["alloc", "embedded_graphics"]

[[example]]
name = "button_click"
path = "../examples/button_click.rs"
required-features = ["alloc", "embedded_graphics"]

[[example]]
name = "scale"
path = "../examples/scale.rs"
required-features = ["alloc", "embedded_graphics"]

[[example]]
name = "arc"
path = "../examples/arc.rs"
required-features = ["alloc", "embedded_graphics"]

[[example]]
name = "sdl"
path = "../examples/sdl.rs"
required-features = ["alloc", "drivers"]

[[example]]
name = "sdl_demo"
path = "../examples/sdl_demo.rs"
required-features = ["sdl"]

[[example]]
name = "rust_timer"
path = "../examples/rust_timer.rs"
required-features = ["alloc", "embedded_graphics", "rust_timer"]

[[example]]
name = "animation"
path = "../examples/animation.rs"
required-features = ["alloc", "embedded_graphics"]
